name: CI

on: 
  workflow_dispatch:
    inputs:
      production:
        type: choice
        description: '选择固件型号：'
        options:
        - K2P
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: 初始环境设置
        run: |
          sudo apt-get update && sudo timedatectl set-timezone "Asia/Shanghai"
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext
      - name: 准备工具链
        run: |
          cd toolchain-mipsel && sh dl_toolchain.sh
      - name: 开始编译
        run: |
          mkdir -p /opt/images && cd trunk
          sudo ./build_firmware_ci ${{ github.event.inputs.production }}
          sudo mv -f images/*.trx /opt/images && sudo ./clear_tree
      - name: 上传固件到Artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Padavan-4.4
          path: /opt/images
